const actions = {
    ADD_TODO : 'ADD_TODO' , 
    CHANGE_TODO : 'CHANGE_TODO',
    DELETE_TODO : 'DELETE_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    UNCOMPLETE_TODO: 'UNCOMPLETE_TODO',
    SHOW_ALL : 'SHOW_ALL',
    SHOW_COMPLETED : 'SHOW_COMPLETED',
    SHOW_UNCOMPLETED : 'SHOW_UNCOMPLETED'
}

module.exports = actions;